### ISSUE TITLE
User friendly navigation and responsive design

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/One-fitness#1]
**User story**
As a First-time visitor, I would like to be able to navigate to different parts of the website with relative ease, so I can find the information I need without frustration. Additionally the website should be responsive across multiple devices.

**Acceptance Criteria**
- [x] The website is responsive across most used devices and screen sizes.
- [x] Site structure is efficient and allows the user to easily find and use all elements of the page.

**Tasks**
- [x] Apply Bootstrap grids to make the website accessible to most would be users.
- [x] Arrange the site layout and navigation based on best practices, ensuring all key sections and pages are easily accessible.
