### ISSUE TITLE
Discount section or discount displayed on home page

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/One-fitness#2]
**User Story:**
As a user I would like to be able to quickly see any potential for discounts or savings within the gym 

**Acceptance criteria**

- [x] Users must be able to see this quickly or immediately after opening the page
- [x] This section must stand out and be eye catching

**Tasks**

- [x] Create a discount section, button or even a modal which pops up on the home screen on opening of the page
- [x] Make sure this element of the web page stands out, by color, image or anything else
- [x] Add CTA button to this element
