### ISSUE TITLE
User reviews

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/One-fitness#3]
User story:
As a new potential customer I would like to be able to see reviews from past gym guests to understand how others experience was within the gym

**Acceptance criteria**
- [ ] Must show reviews from previous or current gym guests
- [ ] A whole section must be dedicated to display the customer reviews

**Tasks**

- [ ] Create a static section on the website for customer reviews
- [ ] Add a name, review and if possible stars
