### ISSUE TITLE
Personal trainers booking

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/One-fitness#4]
**User story:**
As a new gym goer I would like to be able to book sessions with a personal trainer so I can get
help and advice on my new gym training and lifestyle

**Acceptance criteria**
- [ ] Users must be able to fill out a form of who they would like to book their session with and when
- [ ] Users must be able to see information about personal trainers so they can decide which one they want
- [ ] 

**Tasks**
- [ ] Create a new link to a page which displays different trainers 
- [ ] Create a fillable form for users to be able to book sessions with different personal trainers
