### ISSUE TITLE
Display gym amenities

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/One-fitness#5]
**User story:**
As a fitness enthusiast I would like to be able to see what amenities and
other services the gym has to offer other than weight lifting and excercise

**Acceptance criteria**
- [ ] Amenities must be shown on its own page and in the home page
- [ ] Images must be shown to display our services to and entice customers

**Tasks**

- [x] Create a summarised Amenities section on the home page
- [ ] Create a amenities page which displays all our gym has to offer on this front
- [ ] Create each amenity in the form of a card
