### ISSUE TITLE
Book classes

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/One-fitness#6]
User story:
As a user I would like to be able to book classes at the click of a button so I can come whenever I want

**Acceptance criteria**
- [ ] A button/link directing to this booking form must be found in the nav and classes page
- [ ] There must be either on the same or a separate page a form to fill out to book classes

**Tasks**
- [ ] Create a Button/link in the booking page 
- [ ] Create a form to book classes either on a separate page or in the booking page
- [ ] Ensure proper html form validation
