### ISSUE TITLE
Gym classes

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/One-fitness#8]
**User story:**
As a Fitness enthusiast I would like to be able to see detailed information of the different classes available to customers so I can decide if this is the right gym for me 

**Acceptance criteria**
- [x] Must have a separate page displaying the classes in the gym and a small summarised section on the home page
- [x] Each different kind of class will showcase an image of said class and description

**Tasks**
- [x] Create a separate page to showcase all our classes
- [x] Create a classes section in the homepage to give a bit of an introduction into our gym classes
- [x] Add each class ino the classes page in a card format, showcasing an image of each class and descriptions
- [x] Showcase each classes time either individually or on a table accessible somewhere on the classes page (at the bottom may be best after displaying all different available classes)
