### ISSUE TITLE
CTA button

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/One-fitness#9]
**User story:**
As a new user I would like to easily be able to navigate to the gym sign up to apply for a gym membership

**Acceptance criteria**
- [x] This will be the CTA button, this button MUST stand out and be very visible from the first opening of the page
- [x] This button will be located in multiple spots. wherein users might want to signup after seeing

**Tasks**
- [x] Create our CTA button in the navigation bar, visible regardless of which responsive design, from mobile to large screen
- [x] Add our CTA button to different sections like in our gyms discount section
